# Generated by Django 5.2 on 2025-06-12 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payee_name",
                    models.CharField(max_length=255, verbose_name="Payee Name"),
                ),
                (
                    "payee_email",
                    models.EmailField(
                        max_length=254, verbose_name="Payee Email Address"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "gcash_receipt_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="gcash_receipts/",
                        verbose_name="GCash Receipt Image",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
