# Generated by Django 5.1.2 on 2025-07-30 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_options_payment_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gcash_receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payee_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payee_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(upload_to='payment_qr_codes/', verbose_name='Payment QR Code')),
                ('title', models.CharField(default='General Payment QR Code', max_length=100, verbose_name='QR Code Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_qr_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment QR Code',
                'verbose_name_plural': 'Payment QR Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
