# Generated by Django 5.2.5 on 2025-08-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_gcash_receipt_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('registration', 'Registration'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
