# Generated by Django 6.0 on 2025-12-31 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_payments_pa_user_id_2ff331_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_qr_code', models.ImageField(blank=True, null=True, upload_to='system_qr_codes/', verbose_name='Registration QR Code')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_payment_05904b_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='QR-PH', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='payment',
            name='qr_ph_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='QR PH Reference'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='Payment Receipt'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Reference Number'),
        ),
        migrations.AddField(
            model_name='payment',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Rejection Reason'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference_number'], name='payments_pa_referen_c54e4c_idx'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_config_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='gcash_receipt_image',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
    ]
