# Generated by Django 5.2.7 on 2025-10-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_qr_ph_paymongo_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('body', models.TextField(blank=True)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
