# Generated by Django 6.0 on 2026-01-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_systemconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Registration Fee'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='registration_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='system_qr_codes/', verbose_name='Registration QR Code (Legacy)'),
        ),
    ]
