# Generated by Django 5.1.2 on 2025-07-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Event Fee'),
        ),
        migrations.AddField(
            model_name='event',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='event_qr_codes/', verbose_name='Payment QR Code'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_notes',
            field=models.TextField(blank=True, verbose_name='Payment Notes'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Payment Not Required'), ('pending', 'Payment Pending'), ('paid', 'Payment Verified'), ('rejected', 'Payment Rejected')], default='not_required', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_receipts/', verbose_name='Payment Receipt'),
        ),
    ]
