# Generated by Django 4.2.7 on 2025-08-07 02:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_event_payment_amount_event_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='amount_required',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Amount Required'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Amount Paid'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Payment Not Required'), ('pending', 'Payment Pending'), ('partial', 'Partial Payment'), ('paid', 'Payment Complete'), ('rejected', 'Payment Rejected')], default='not_required', max_length=20),
        ),
        migrations.CreateModel(
            name='EventPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment Amount')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='event_payment_receipts/', verbose_name='Payment Receipt')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Payment Notes')),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='events.eventregistration')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_event_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
