# Generated by Django 5.0.7 on 2025-08-07 10:10

from django.db import migrations
from decimal import Decimal

def update_amount_required(apps, schema_editor):
    EventRegistration = apps.get_model('events', 'EventRegistration')
    
    # Update all registrations to have the correct amount_required
    for registration in EventRegistration.objects.all():
        if registration.event.payment_amount:
            registration.amount_required = registration.event.payment_amount
        else:
            registration.amount_required = Decimal('0.00')
        registration.save()

def reverse_update_amount_required(apps, schema_editor):
    EventRegistration = apps.get_model('events', 'EventRegistration')
    
    # Reset amount_required to 0
    EventRegistration.objects.all().update(amount_required=Decimal('0.00'))

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventregistration_amount_required_and_more'),
    ]

    operations = [
        migrations.RunPython(update_amount_required, reverse_update_amount_required),
    ]
