# Generated by Django 5.2.6 on 2025-09-27 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20250807_1010'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventpayment',
            index=models.Index(fields=['registration', 'status', 'created_at'], name='events_even_registr_05fed9_idx'),
        ),
    ]
