# Generated by Django 5.2.7 on 2025-10-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventpayment_events_even_registr_05fed9_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Payment Not Required'), ('paid', 'Paid'), ('rejected', 'Payment Rejected')], default='not_required', max_length=20),
        ),
    ]
