# Generated by Django 6.0 on 2025-12-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventpayment_events_even_registr_05fed9_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpayment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Reference Number'),
        ),
        migrations.AddField(
            model_name='eventpayment',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Rejection Reason'),
        ),
    ]
