# Generated by Django 6.0 on 2026-01-01 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventpayment_reference_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpayment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Expiration'),
        ),
        migrations.AddField(
            model_name='eventpayment',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventpayment',
            name='payment_method',
            field=models.CharField(choices=[('paymongo_gcash', 'GCash via PayMongo'), ('paymongo_maya', 'Maya via PayMongo'), ('paymongo_grabpay', 'GrabPay via PayMongo'), ('manual', 'Manual Upload')], default='paymongo_gcash', max_length=20),
        ),
        migrations.AddField(
            model_name='eventpayment',
            name='paymongo_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='PayMongo Payment ID'),
        ),
        migrations.AddField(
            model_name='eventpayment',
            name='paymongo_source_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='PayMongo Source ID'),
        ),
        migrations.AlterField(
            model_name='eventpayment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='eventpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='eventpayment',
            index=models.Index(fields=['paymongo_source_id'], name='events_even_paymong_ea4ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='eventpayment',
            index=models.Index(fields=['paymongo_payment_id'], name='events_even_paymong_fffc6a_idx'),
        ),
    ]
