# Generated by Django 6.0 on 2026-01-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_eventpayment_expires_at_eventpayment_is_expired_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='eventpayment',
            name='payment_method',
            field=models.CharField(choices=[('paymongo_gcash', 'GCash via PayMongo'), ('paymongo_maya', 'Maya via PayMongo'), ('manual', 'Manual Upload')], default='paymongo_gcash', max_length=20),
        ),
    ]
