# Generated by Django 5.2.7 on 2025-10-24 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_migrate_event_payment_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='event',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set event fee amount. Leave blank for free events.', max_digits=10, null=True, verbose_name='Event Fee'),
        ),
        # NOTE: The paymongo_ fields are present in the initial migration state for this repo.
        # The AddField operations that would duplicate those columns were removed to avoid
        # attempting to create columns that already exist in a clean database when running
        # migrations from scratch (this repo historically had schema drift and some fields
        # were already included in 0001_initial). The index on `paymongo_payment_id` is
        # already declared in the initial migration as well.
    ]
