# Generated by Django 6.0 on 2026-01-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_event_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpayment',
            name='paymongo_checkout_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='PayMongo Checkout URL'),
        ),
    ]
