# Generated by Django 6.0 on 2026-01-02 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_eventpayment_paymongo_checkout_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Session Active')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('auto_stop_minutes', models.IntegerField(default=0, help_text='Auto-stop after X minutes (0 = manual only)')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_session', to='events.event')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_attendance_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_image', models.ImageField(help_text='Upload certificate template image', upload_to='certificate_templates/')),
                ('name_x', models.IntegerField(default=500, help_text='X coordinate for participant name')),
                ('name_y', models.IntegerField(default=400, help_text='Y coordinate for participant name')),
                ('name_font_size', models.IntegerField(default=60, help_text='Font size for participant name')),
                ('name_color', models.CharField(default='#000000', help_text='Hex color for name (e.g., #000000)', max_length=7)),
                ('event_name_x', models.IntegerField(default=500, help_text='X coordinate for event name')),
                ('event_name_y', models.IntegerField(default=550, help_text='Y coordinate for event name')),
                ('event_font_size', models.IntegerField(default=40, help_text='Font size for event name')),
                ('event_color', models.CharField(default='#000000', help_text='Hex color for event name', max_length=7)),
                ('date_x', models.IntegerField(default=500, help_text='X coordinate for date')),
                ('date_y', models.IntegerField(default=650, help_text='Y coordinate for date')),
                ('date_font_size', models.IntegerField(default=30, help_text='Font size for date')),
                ('date_color', models.CharField(default='#000000', help_text='Hex color for date', max_length=7)),
                ('cert_number_x', models.IntegerField(default=100, help_text='X coordinate for certificate number')),
                ('cert_number_y', models.IntegerField(default=100, help_text='Y coordinate for certificate number')),
                ('cert_number_font_size', models.IntegerField(default=20, help_text='Font size for certificate number')),
                ('cert_number_color', models.CharField(default='#666666', help_text='Hex color for cert number', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_template', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(help_text='Unique certificate identifier', max_length=50, unique=True)),
                ('certificate_file', models.ImageField(help_text='Generated certificate PNG', upload_to='event_certificates/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='events.attendance')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'unique_together': {('user', 'event')},
            },
        ),
    ]
