# Generated by Django 5.2.7 on 2025-11-08 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_attendance_qrcode'),
        ('events', '0014_fix_eventregistration_pk'),
    ]

    operations = [
    ]
