# Generated by Django 5.2.7 on 2025-11-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_merge_20251108_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Payment Not Required'), ('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Payment Rejected')], default='not_required', max_length=20),
        ),
    ]
