# Generated by Django 5.2.7 on 2025-11-20 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_eventregistration_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_image', models.ImageField(help_text='Background certificate design image (PNG or JPG recommended)', upload_to='certificate_templates/')),
                ('certificate_name', models.CharField(default='Certificate of Participation', help_text='Title/name of the certificate', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_x', models.IntegerField(default=600, help_text='X pixel position for scout name')),
                ('name_y', models.IntegerField(default=450, help_text='Y pixel position for scout name')),
                ('name_font_size', models.IntegerField(default=48, help_text='Font size for scout name')),
                ('name_color', models.CharField(default='#000000', help_text='Font color for name (hex format, e.g., #000000)', max_length=7)),
                ('event_x', models.IntegerField(default=600, help_text='X pixel position for event name')),
                ('event_y', models.IntegerField(default=520, help_text='Y pixel position for event name')),
                ('event_font_size', models.IntegerField(default=32, help_text='Font size for event name')),
                ('event_color', models.CharField(default='#333333', help_text='Font color for event name', max_length=7)),
                ('date_x', models.IntegerField(default=600, help_text='X pixel position for date')),
                ('date_y', models.IntegerField(default=590, help_text='Y pixel position for date')),
                ('date_font_size', models.IntegerField(default=28, help_text='Font size for date')),
                ('date_color', models.CharField(default='#666666', help_text='Font color for date', max_length=7)),
                ('certificate_number_x', models.IntegerField(blank=True, help_text='X pixel position for certificate number', null=True)),
                ('certificate_number_y', models.IntegerField(blank=True, help_text='Y pixel position for certificate number', null=True)),
                ('certificate_number_font_size', models.IntegerField(default=16, help_text='Font size for certificate number')),
                ('certificate_number_color', models.CharField(default='#999999', help_text='Font color for certificate number', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active for use')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_certificate_templates', to=settings.AUTH_USER_MODEL)),
                ('event', models.OneToOneField(help_text='Event this certificate template is for', on_delete=django.db.models.deletion.CASCADE, related_name='certificate_template', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_image', models.ImageField(help_text='Generated certificate PNG image', upload_to='certificates/%Y/%m/%d/')),
                ('certificate_number', models.CharField(help_text='Unique certificate number for tracking', max_length=255, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True, help_text='When the certificate was generated')),
                ('download_count', models.IntegerField(default=0, help_text='Number of times certificate has been downloaded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_template', models.ForeignKey(blank=True, help_text='Template used to generate this certificate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_certificates', to='events.certificatetemplate')),
                ('event', models.ForeignKey(help_text='Event this certificate is for', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='events.event')),
                ('user', models.ForeignKey(help_text='Scout receiving this certificate', on_delete=django.db.models.deletion.CASCADE, related_name='event_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_date'],
                'indexes': [models.Index(fields=['event', 'user'], name='events_even_event_i_b7c0aa_idx'), models.Index(fields=['certificate_number'], name='events_even_certifi_529f19_idx')],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
