# Generated by Django 5.2 on 2025-06-12 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page View"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("action", "User Action"),
                            ("registration", "Registration"),
                            ("profile_update", "Profile Update"),
                            ("password_change", "Password Change"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("page_url", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event_type"], name="analytics_a_event_t_a460ec_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="analytics_a_timesta_aef2a5_idx"
                    ),
                    models.Index(
                        fields=["user"], name="analytics_a_user_id_3326ea_idx"
                    ),
                ],
            },
        ),
    ]
