# Generated by Django 5.1.2 on 2025-07-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('admin', 'Administrator'), ('scout', 'Scout'), ('senior_scout', 'Senior Scout'), ('patrol_leader', 'Patrol Leader'), ('assistant_patrol_leader', 'Assistant Patrol Leader'), ('second_class', 'Second Class'), ('first_class', 'First Class'), ('star', 'Star'), ('life', 'Life'), ('eagle', 'Eagle')], default='scout', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='username'),
        ),
    ]
