# Generated by Django 4.2.7 on 2025-08-07 02:50

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_registration_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_amount_required',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10, verbose_name='Registration Amount Required'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_total_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Registration Paid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_status',
            field=models.CharField(choices=[('pending_payment', 'Pending Registration Payment'), ('payment_submitted', 'Registration Payment Submitted'), ('partial_payment', 'Partial Registration Payment'), ('payment_verified', 'Registration Payment Verified'), ('active', 'Active Member'), ('inactive', 'Inactive')], default='pending_payment', max_length=30),
        ),
        migrations.CreateModel(
            name='RegistrationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment Amount')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='registration_payment_receipts/', verbose_name='Payment Receipt')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Payment Notes')),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_payments', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_registration_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
