# Generated by Django 5.2.5 on 2025-08-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_registration_amount_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
