# Generated by Django 4.2.7 on 2025-08-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_membership_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
