# Generated by Django 5.2.6 on 2025-09-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_registration_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registrationpayment',
            index=models.Index(fields=['user', 'status', 'created_at'], name='accounts_re_user_id_00803b_idx'),
        ),
    ]
