# Generated by Django 5.2.7 on 2025-10-17 11:34

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_normalize_phone_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('registrar_name', models.CharField(max_length=200, verbose_name='Teacher/Registrar Name')),
                ('registrar_email', models.EmailField(max_length=254, verbose_name='Teacher/Registrar Email')),
                ('registrar_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='PH', verbose_name='Teacher/Registrar Phone')),
                ('number_of_students', models.PositiveIntegerField(default=1, verbose_name='Number of Students')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('amount_per_student', models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Amount per Student')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Payment Successful'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('paymongo_source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('paymongo_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registrar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_registrations_created', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_batch_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='registrationpayment',
            name='batch_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_payments', to='accounts.batchregistration', verbose_name='Part of Batch Registration'),
        ),
        migrations.AddIndex(
            model_name='batchregistration',
            index=models.Index(fields=['batch_id'], name='accounts_ba_batch_i_3452a3_idx'),
        ),
        migrations.AddIndex(
            model_name='batchregistration',
            index=models.Index(fields=['status', 'created_at'], name='accounts_ba_status_3643e5_idx'),
        ),
    ]
