# Generated by Django 6.0 on 2025-12-23 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_normalize_phone_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_by',
            field=models.ForeignKey(blank=True, help_text='The teacher who manages this student account (if applicable)', limit_choices_to={'rank': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_students', to=settings.AUTH_USER_MODEL, verbose_name='Managed by Teacher'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('admin', 'Administrator'), ('teacher', 'Teacher'), ('scout', 'Scout')], default='scout', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_status',
            field=models.CharField(choices=[('pending_payment', 'Pending Registration Payment'), ('payment_submitted', 'Registration Payment Submitted'), ('partial_payment', 'Partial Registration Payment'), ('payment_verified', 'Registration Payment Verified'), ('active', 'Active Member'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('suspended', 'Suspended')], default='pending_payment', max_length=30),
        ),
    ]
