# Generated by Django 5.2.7 on 2025-10-17 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_batchregistration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchStudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('password_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_data', to='accounts.batchregistration')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_student_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['batch_registration', 'email'], name='accounts_ba_batch_r_e5cc3e_idx')],
            },
        ),
    ]
