# Generated by Django 6.0 on 2025-12-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_managed_by_alter_user_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpayment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Reference Number'),
        ),
        migrations.AddField(
            model_name='registrationpayment',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Rejection Reason'),
        ),
    ]
