# Generated by Django 5.2.7 on 2025-10-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_batchstudentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpayment',
            name='paymongo_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PayMongo Payment ID'),
        ),
        migrations.AddField(
            model_name='registrationpayment',
            name='paymongo_source_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PayMongo Source ID'),
        ),
    ]
