# Generated by Django 6.0 on 2026-01-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_registrationpayment_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpayment',
            name='payment_method',
            field=models.CharField(choices=[('paymongo_gcash', 'GCash via PayMongo'), ('paymongo_maya', 'Maya via PayMongo'), ('manual', 'Manual Upload')], default='paymongo_gcash', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='registrationpayment',
            name='paymongo_checkout_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='PayMongo Checkout URL'),
        ),
        migrations.AddField(
            model_name='registrationpayment',
            name='paymongo_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PayMongo Payment ID'),
        ),
        migrations.AddField(
            model_name='registrationpayment',
            name='paymongo_source_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PayMongo Source ID'),
        ),
        migrations.AlterField(
            model_name='registrationpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
