# Generated by Django 5.2.7 on 2025-10-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_registrationpayment_paymongo_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=30),
        ),
    ]
