# Generated by Django 6.0 on 2026-01-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_registrationpayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrator'), ('teacher', 'Teacher'), ('scout', 'Scout')], default='scout', max_length=30, null=True),
        ),
    ]
