# Generated by Django 5.2.7 on 2025-11-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_migrate_registration_status_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=500.0, help_text='Default fee for new user registrations. All users pay this amount to register.', max_digits=10, verbose_name='Platform Registration Fee')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('scout', 'Scout'), ('leader', 'Scout Leader'), ('admin', 'Administrator')], default='scout', help_text='Scout (member), Scout Leader (coordinator), or Administrator', max_length=30, verbose_name='User Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='scout_rank',
            field=models.CharField(blank=True, choices=[('tenderfoot', 'Tenderfoot'), ('second_class', 'Second Class'), ('first_class', 'First Class'), ('star', 'Star'), ('life', 'Life'), ('eagle', 'Eagle Scout')], help_text='Merit-based advancement rank (for scouts only)', max_length=30, null=True, verbose_name='Scout Advancement Rank'),
        ),
        migrations.AlterField(
            model_name='batchregistration',
            name='amount_per_student',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Will be set to current platform registration fee automatically', max_digits=10, verbose_name='Amount per Student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('scout', 'Scout'), ('leader', 'Scout Leader'), ('admin', 'Administrator'), ('tenderfoot', 'Tenderfoot'), ('second_class', 'Second Class'), ('first_class', 'First Class'), ('star', 'Star'), ('life', 'Life'), ('eagle', 'Eagle Scout')], default='scout', help_text="DEPRECATED: Use 'role' field instead", max_length=30),
        ),
    ]
