# Generated by Django 5.2.7 on 2025-11-15 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_systemsettings_user_role_user_scout_rank_and_more'),
    ]

    operations = [
        # Remove batch-related fields from RegistrationPayment
        migrations.RemoveField(
            model_name='registrationpayment',
            name='batch_registration',
        ),
        # Add teacher relationship fields
        migrations.AddField(
            model_name='registrationpayment',
            name='paid_by_teacher',
            field=models.ForeignKey(
                blank=True,
                help_text='If this registration was paid by a teacher during bulk registration',
                limit_choices_to={'role': 'teacher'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='teacher_paid_registrations',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Paid by Teacher'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='registered_by_teacher',
            field=models.ForeignKey(
                blank=True,
                help_text='The teacher who registered this student (if applicable)',
                limit_choices_to={'role': 'teacher'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='registered_students',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Registered by Teacher'
            ),
        ),
        # Update role choices to include teacher
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(
                choices=[
                    ('scout', 'Scout'),
                    ('teacher', 'Teacher'),
                    ('leader', 'Scout Leader'),
                    ('admin', 'Administrator'),
                    ('tenderfoot', 'Tenderfoot'),
                    ('second_class', 'Second Class'),
                    ('first_class', 'First Class'),
                    ('star', 'Star'),
                    ('life', 'Life'),
                    ('eagle', 'Eagle Scout')
                ],
                default='scout',
                help_text="DEPRECATED: Use 'role' field instead",
                max_length=30
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('scout', 'Scout'),
                    ('teacher', 'Teacher'),
                    ('leader', 'Scout Leader'),
                    ('admin', 'Administrator')
                ],
                default='scout',
                help_text='Scout (member), Scout Leader (coordinator), or Administrator',
                max_length=30,
                verbose_name='User Role'
            ),
        ),
    ]
