# Generated by Django 5.2.7 on 2025-11-23 05:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Campaign Title')),
                ('description', models.TextField(verbose_name='Campaign Description')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='donation_banners/', verbose_name='Banner Image')),
                ('qr_code_image', models.ImageField(blank=True, help_text='Optional static QR code for display (actual payment uses dynamic QR codes)', null=True, upload_to='donation_qr_codes/', verbose_name='QR Code Image')),
                ('external_payment_details', models.TextField(blank=True, help_text='Additional payment information or instructions', verbose_name='External Payment Details')),
                ('goal_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Target amount to raise. Leave blank for no goal.', max_digits=10, null=True, verbose_name='Goal Amount')),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Automatically calculated from verified donations', max_digits=10, verbose_name='Current Amount Raised')),
                ('start_date', models.DateField(blank=True, help_text='Campaign start date (optional)', null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Campaign end date (optional)', null=True, verbose_name='End Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Campaign Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal_reached', models.BooleanField(default=False, help_text='Automatically set when current_amount >= goal_amount', verbose_name='Goal Reached')),
                ('goal_reached_date', models.DateTimeField(blank=True, null=True, verbose_name='Goal Reached Date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Donation Campaign',
                'verbose_name_plural': 'Donation Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Donation Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('paymongo_source_id', models.CharField(blank=True, help_text='PayMongo source ID for QR PH payment', max_length=255, null=True, verbose_name='PayMongo Source ID')),
                ('paymongo_payment_id', models.CharField(blank=True, help_text='PayMongo payment ID after successful payment', max_length=255, null=True, verbose_name='PayMongo Payment ID')),
                ('payment_method', models.CharField(default='gcash', max_length=50, verbose_name='Payment Method')),
                ('gateway_response', models.JSONField(blank=True, help_text='Full response from PayMongo API', null=True, verbose_name='Gateway Response Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('message', models.TextField(blank=True, help_text='Optional message from the donor', verbose_name='Donor Message')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Hide donor name from public donor list', verbose_name='Anonymous Donation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL, verbose_name='Donor')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.donationcampaign', verbose_name='Campaign')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'status', 'created_at'], name='donations_d_campaig_6afdf2_idx'), models.Index(fields=['user', 'status'], name='donations_d_user_id_53d869_idx'), models.Index(fields=['paymongo_payment_id'], name='donations_d_paymong_fce87f_idx')],
            },
        ),
    ]
